import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Layout from "@/components/shared/Layout"
import RainbowKitAndWagmiProvider from "./RainbowKitAndWagmiProvider"
import { Toaster } from "sonner"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Voting",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/logo.png",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RainbowKitAndWagmiProvider>
          <Layout>
            {children}
            <Toaster />
          </Layout>
        </RainbowKitAndWagmiProvider>
      </body>
    </html>
  )
}
